[Icon Theme]
Name=Diagonal-kde
Name[en_GB]=Diagonal-kde
Name[hu]=Diagonal-kde

Comment=A custom icon pack inspired by popular icon themes (Yaru, Evolvere, WhiteSur, etc.).
Comment[en_GB]=A custom icon pack inspired by popular icon themes (Yaru, Evolvere, WhiteSur, etc.).
Comment[hu]=Saját készítésű ikoncsomag, amit a népszerű ikontémák (Yaru, Evolvere, WhiteSur, stb.) ihlettek.

DisplayDepth=32
Example=folder
FollowsColorScheme=true
Inherits=breeze,hicolor

DesktopDefault=48
DesktopSizes=16,22,24,32,48,64,96,128,256
ToolbarDefault=22
ToolbarSizes=16,22,24,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,24,32,48
SmallDefault=16
SmallSizes=16,22,24,32,48
PanelDefault=48
PanelSizes=16,22,24,32,48,64,96,128,256
DialogDefault=48
DialogSizes=16,22,24,32,48,64,96,128,256

########## Directories

Directories=actions/12,actions/16,actions/22,actions/24,actions/32,actions/48,actions/64,animations/16,animations/22,applets/16,applets/22,applets/24,applets/32,applets/48,applets/64,applets/128,applets/256,apps/16,apps/32,apps/48,apps/64,categories/32,devices/16,devices/22,devices/24,devices/32,devices/64,emblems/8,emblems/16,emblems/22,emblems/24,emotes/22,mimetypes/16,mimetypes/22,mimetypes/24,mimetypes/32,mimetypes/64,places/16,places/22,places/24,places/32,places/48,places/64,places/96,preferences/32,status/16,status/22,status/24,status/32,status/64
ScaledDirectories=actions/16@2x,actions/16@3x,actions/22@2x,actions/22@3x,actions/24@2x,actions/24@3x,actions/32@2x,actions/32@3x,animations/16@2x,animations/16@3x,applets/24@2x,applets/24@3x,apps/16@2x,apps/16@3x,devices/16@2x,devices/16@3x,devices/22@2x,devices/22@3x,devices/24@2x,devices/24@3x,emblems/16@2x,emblems/16@3x,emblems/22@2x,emblems/22@3x,emblems/24@2x,emblems/24@3x,emotes/22@2x,emotes/22@3x,mimetypes/16@2x,mimetypes/16@3x,mimetypes/22@2x,mimetypes/22@3x,mimetypes/24@2x,mimetypes/24@3x,places/16@2x,places/16@3x,places/22@2x,places/22@3x,places/24@2x,places/24@3x,preferences/24@2x,status/16@2x,status/16@3x,status/22@2x,status/22@3x,status/24@2x,status/24@3x


########## 12x12

[actions/12]
Size=12
Context=Actions
Type=Fixed

########## 16x16

[actions/16]
Size=16
Context=Actions
Type=Fixed

[actions/16@2x]
Size=16
Scale=2
Context=Actions
Type=Fixed

[actions/16@3x]
Size=16
Scale=3
Context=Actions
Type=Fixed

[actions/22]
Size=22
Context=Actions
Type=Fixed

[actions/22@2x]
Size=22
Scale=2
Context=Actions
Type=Fixed

[actions/22@3x]
Size=22
Scale=3
Context=Actions
Type=Fixed

[actions/24]
Size=24
Context=Actions
Type=Fixed

[actions/24@2x]
Size=24
Scale=2
Context=Actions
Type=Fixed

[actions/24@3x]
Size=24
Scale=3
Context=Actions
Type=Fixed

[actions/32]
Size=32
Context=Actions
Type=Fixed

[actions/32@2x]
Size=32
Scale=2
Type=Fixed

[actions/32@3x]
Size=32
Scale=3
Type=Fixed

[actions/48]
Size=48
Context=Actions
Type=Scalable
MinSize=48
MaxSize=256

[actions/64]
Size=64
Context=Actions
Type=Scalable
MinSize=64
MaxSize=256


########## Animations

[animations/16]
Size=16
Context=Animations
Type=Fixed

[animations/16@2x]
Size=16
Scale=2
Context=Animations
Type=Fixed

[animations/16@3x]
Size=16
Scale=3
Context=Animations
Type=Fixed

[animations/22]
Size=22
Context=Animations
Type=Scalable
MinSize=22
MaxSize=256

########## Applets

[applets/16]
Size=16
Context=Status
Type=Fixed

[applets/22]
Size=22
Context=Status
Type=Fixed

[applets/24]
Size=24
Context=Status
Type=Fixed

[applets/24@2x]
Size=24
Scale=2
Context=Status
Type=Fixed

[applets/24@3x]
Size=24
Scale=3
Context=Status
Type=Fixed

[applets/32]
Size=32
Context=Status
Type=Scalable
MinSize=32
MaxSize=256

[applets/48]
Size=48
Context=Status
Type=Scalable
MinSize=48
MaxSize=256

[applets/64]
Size=64
Context=Status
Type=Scalable
MinSize=64
MaxSize=256

[applets/128]
Size=128
Context=Applications
Type=Scalable
MinSize=32
MaxSize=256

[applets/256]
Size=256
Context=Applications
Type=Scalable
MinSize=48
MaxSize=256

########## Apps

[apps/16]
Size=16
Context=Applications
Type=Fixed

[apps/16@2x]
Size=16
Scale=2
Context=Applications
Type=Fixed

[apps/16@3x]
Size=16
Scale=3
Context=Applications
Type=Fixed

[apps/32]
Size=32
Context=Applications
Type=Scalable
MinSize=32
MaxSize=256

[apps/48]
Size=48
Context=Applications
Type=Scalable
MinSize=48
MaxSize=256

[apps/64]
Size=64
Context=Applications
Type=Scalable
MinSize=24
MaxSize=256

########## Categories

[categories/32]
Size=32
Context=Categories
Type=Scalable
MinSize=32
MaxSize=256

########## Devices

[devices/16]
Size=16
Context=Devices
Type=Fixed

[devices/16@2x]
Size=16
Scale=2
Context=Devices
Type=Fixed

[devices/16@3x]
Size=16
Scale=3
Context=Devices
Type=Fixed

[devices/22]
Size=22
Context=Devices
Type=Fixed

[devices/22@2x]
Size=22
Scale=2
Context=Devices
Type=Fixed

[devices/22@3x]
Size=22
Scale=3
Context=Devices
Type=Fixed

[devices/24]
Size=24
Context=Devices
Type=Fixed

[devices/24@2x]
Size=24
Scale=2
Context=Devices
Type=Fixed

[devices/24@3x]
Size=24
Scale=3
Context=Devices
Type=Fixed

[devices/32]
Size=32
Context=Devices
Type=Fixed

[devices/64]
Size=64
Context=Devices
Type=Scalable
MinSize=24
MaxSize=256

########## Emblems

[emblems/8]
Size=8
Context=Emblems
Type=Fixed

[emblems/16]
Size=16
Context=Emblems
Type=Fixed

[emblems/16@2x]
Size=16
Scale=2
Context=Emblems
Type=Fixed

[emblems/16@3x]
Size=16
Scale=3
Context=Emblems
Type=Fixed

[emblems/22]
Size=22
Context=Emblems
Type=Fixed

[emblems/22@2x]
Size=22
Scale=2
Context=Emblems
Type=Fixed

[emblems/22@3x]
Size=22
Scale=3
Context=Emblems
Type=Fixed

[emblems/24]
Size=24
Context=Emblems
Type=Fixed

[emblems/24@2x]
Size=24
Scale=2
Context=Emblems
Type=Fixed

[emblems/24@3x]
Size=24
Scale=3
Context=Emblems
Type=Fixed


########## Emoticons

[emotes/22]
Size=22
Context=Emotes
Type=Fixed

[emotes/22@2x]
Size=22
Scale=2
Context=Emotes
Type=Fixed

[emotes/22@3x]
Size=22
Scale=3
Context=Emotes
Type=Fixed


########## Mimetypes

[mimetypes/16]
Size=16
Context=MimeTypes
Type=Fixed
MinSize=16

[mimetypes/16@2x]
Size=16
Scale=2
Context=MimeTypes
Type=Fixed
MinSize=16

[mimetypes/16@3x]
Size=16
Scale=3
Context=MimeTypes
Type=Fixed
MinSize=16

[mimetypes/22]
Size=22
Context=MimeTypes
Type=Scalable
MinSize=22
MaxSize=24

[mimetypes/22@2x]
Size=22
Scale=2
Context=MimeTypes
Type=Scalable
MinSize=22
MaxSize=24

[mimetypes/22@3x]
Size=22
Scale=3
Context=MimeTypes
Type=Scalable
MinSize=22
MaxSize=24

[mimetypes/24]
Size=24
Context=MimeTypes
Type=Scalable
MinSize=24
MaxSize=24

[mimetypes/24@2x]
Size=24
Scale=2
Context=MimeTypes
Type=Scalable
MinSize=24
MaxSize=24

[mimetypes/24@3x]
Size=24
Scale=3
Context=MimeTypes
Type=Scalable
MinSize=24
MaxSize=24

[mimetypes/32]
Size=32
Context=MimeTypes
Type=Fixed

[mimetypes/64]
Size=64
Context=MimeTypes
Type=Scalable
MinSize=24
MaxSize=256


########## Places

[places/16]
Size=16
Context=Places
Type=Fixed
MinSize=16

[places/16@2x]
Size=16
Scale=2
Context=Places
Type=Fixed
MinSize=16

[places/16@3x]
Size=16
Scale=3
Context=Places
Type=Fixed
MinSize=16

[places/22]
Size=22
Context=Places
Type=Fixed

[places/22@2x]
Size=22
Scale=2
Context=Places
Type=Fixed

[places/22@3x]
Size=22
Scale=3
Context=Places
Type=Fixed

[places/24]
Size=24
Context=Places
Type=Fixed

[places/24@2x]
Size=24
Scale=2
Context=Places
Type=Fixed

[places/24@3x]
Size=24
Scale=3
Context=Places
Type=Fixed

[places/32]
Size=32
Context=Places
Type=Fixed

[places/48]
Size=48
Context=Places
Type=Fixed

[places/64]
Size=64
Context=Places
Type=Scalable
MinSize=24
MaxSize=256

[places/96]
Size=96
Context=Places
Type=Scalable
MinSize=96
MaxSize=256

########## Preferences

[preferences/32]
Size=32
Context=Applications
Type=Scalable
MinSize=32
MaxSize=256

########## Status

[status/16]
Size=16
Context=Status
Type=Fixed

[status/16@2x]
Size=16
Scale=2
Context=Status
Type=Fixed

[status/16@3x]
Size=16
Scale=3
Context=Status
Type=Fixed

[status/22]
Size=22
Context=Status
Type=Fixed

[status/22@2x]
Size=22
Scale=2
Context=Status
Type=Fixed

[status/22@3x]
Size=22
Scale=3
Context=Status
Type=Fixed

[status/24]
Size=24
Context=Status
Type=Fixed

[status/24@2x]
Size=24
Scale=2
Context=Status
Type=Fixed

[status/24@3x]
Size=24
Scale=3
Context=Status
Type=Fixed

[status/32]
Size=32
Context=Status
Type=Fixed

[status/64]
Size=64
Context=Status
Type=Scalable
MinSize=24
MaxSize=256


########## EOF
